name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # - run: npm ci
    - run: npm run deploy

    #发布到mybells.github.io/master
    - name: Deploy wsydxiangwang.github.io/master
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: wsydxiangwang/wsydxiangwang.github.io #可以新建一个mybells.github.io仓库发布到master
        PUBLISH_BRANCH: master
        PUBLISH_DIR: docs/.vuepress/dist
      with:
          emptyCommits: false

    # #发布到MyBlog/gh-pages 查看https://mybells.github.io/MyBlog/，需要修改base配置为MyBlog，修改图片路径
    # - name: Deploy MyBlog/gh-pages
    #   uses: peaceiris/actions-gh-pages@v2
    #   env:
    #     ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    #     PUBLISH_BRANCH: gh-pages #也可以在本项目MyBlog新建gh-pages分支，名字一定要是gh-pages这样github page设置才能识别到这个分支，其他名字识别不到。https://help.github.com/cn/github/working-with-github-pages/creating-a-github-pages-site#creating-your-site
    #     PUBLISH_DIR: docs/.vuepress/dist
    #   with:
    #       emptyCommits: false
